name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack
          
          # Download and install crictl
          CRICTL_VERSION="v1.25.0"
          curl -LO "https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz"
          sudo tar zxvf "crictl-${CRICTL_VERSION}-linux-amd64.tar.gz" -C /usr/local/bin
          rm "crictl-${CRICTL_VERSION}-linux-amd64.tar.gz"

          # Install the latest version of Go
          GO_VERSION="1.20.0"
          curl -LO "https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz"
          sudo tar -C /usr/local -xzf "go${GO_VERSION}.linux-amd64.tar.gz"
          echo "export PATH=\$PATH:/usr/local/go/bin" >> $GITHUB_ENV
          source $GITHUB_ENV

          # Install cri-dockerd
          git clone https://github.com/Mirantis/cri-dockerd.git
          cd cri-dockerd
          mkdir bin
          /usr/local/go/bin/go get
          /usr/local/go/bin/go build -o bin/cri-dockerd
          sudo install bin/cri-dockerd /usr/local/bin/
          sudo cri-dockerd &

      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=none

      - name: Use Minikube's Docker daemon
        run: eval $(minikube docker-env)

      - name: Build Docker image
        run: docker build -t wisecow:v1 ./Container/

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.18.0'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f Kubernetes-manifests/wisecow-deployment.yaml
          kubectl apply -f Kubernetes-manifests/wisecow-service.yaml
